# Generated by Django 3.2.9 on 2021-12-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211213_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='articles',
            new_name='article',
        ),
    ]
